# ---------- Overriding hydra default configs ----------

#hydra:
#  job:
#    name: train
#    chdir: true
#  run:
#    dir: ${dir.OUTPUT_DIR}/${hydra.job.name}/${EXP_NAME}/single
#  sweep:
#    dir: ${dir.OUTPUT_DIR}/${hydra.job.name}/${EXP_NAME}
#    subdir: run${hydra.job.num}

# Dataset
OUTPUT_DIR: '/kaggle/working/'
PRE_LOADED_EEGS: '/Users/yukaisun/Documents/Research/kaggle比賽/kaggle-hms-harmful-brain-activity-classification/data/eeg_specs.npy'
PRE_LOADED_SPECTOGRAMS: '/Users/yukaisun/Documents/Research/kaggle比賽/kaggle-hms-harmful-brain-activity-classification/data/specs.npy'
TRAIN_CSV: "/Users/yukaisun/Documents/Research/kaggle比賽/kaggle-hms-harmful-brain-activity-classification/data/train.csv"
TRAIN_EEGS: "/kaggle/input/brain-eeg-spectrograms/EEG_Spectrograms/"
TRAIN_SPECTOGRAMS: "/kaggle/input/hms-harmful-brain-activity-classification/train_spectrograms/"
TEST_CSV: "/kaggle/input/hms-harmful-brain-activity-classification/test.csv"

defaults: 
  - _self_
  #- model: efficientnet_b0

SEED: 42

# Training
BATCH_SIZE_TRAIN: 32
BATCH_SIZE_VALID: 32
EPOCHS: 4
FOLDS: 5
NUM_WORKERS: 3
num_epochs: 4
LEARNING_RATE: 1e-1
WEIGHT_DECAY: 1e-2
EXP_NAME: 'exp001'
model: efficientnet_b0
monitor: val_loss
monitor_mode: min
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
check_val_every_n_epoch: 1

# 幹我也看不懂
AMP: True
FREEZE: False
GRADIENT_ACCUMULATION_STEPS: 1
MAX_GRAD_NORM: 1e7
NUM_FROZEN_LAYERS: 39
PRINT_FREQ: 20
TRAIN_FULL_DATA: False
VISUALIZE: True